package cn.yellow.entity;

import lombok.Data;

import java.io.Serializable;

@Data
public class huangShiZhe implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huangshizhe.id
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huangshizhe.name
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column huangshizhe.sex
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table huangshizhe
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huangshizhe.id
     *
     * @return the value of huangshizhe.id
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huangshizhe.id
     *
     * @param id the value for huangshizhe.id
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huangshizhe.name
     *
     * @return the value of huangshizhe.name
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huangshizhe.name
     *
     * @param name the value for huangshizhe.name
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column huangshizhe.sex
     *
     * @return the value of huangshizhe.sex
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column huangshizhe.sex
     *
     * @param sex the value for huangshizhe.sex
     *
     * @mbggenerated Tue Dec 19 18:24:13 CST 2017
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }
}